# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - env-dev
      - env-staging
  tags:
    include:
      - '*'
pr: none

pool:
  vmImage: 'windows-latest'

variables:
  frontend: 'reason-digital-news-vue-app'
  CACHE_RESTORED: 'false'
  npm_config_cache: 'reason-digital-news-vue-app\node_modules'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.16.1'
  displayName: 'Install Node.js'

- task: Cache@2
  displayName: 'Cache NPM packages'
  inputs:
    key: 'npm | "$(Agent.OS)" | $(frontend)\package-lock.json'
    restoreKeys: |
       npm | "$(Agent.OS)"
    cacheHitVar: CACHE_RESTORED
    path: $(npm_config_cache)
  condition: and (succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

- task: Npm@1
  displayName: 'NPM install packages'
  inputs:
    command: 'install'
    workingDir: '$(frontend)'
  condition: and (succeeded(), ne(variables.CACHE_RESTORED, 'true'), ne(variables['Build.Reason'], 'PullRequest'))

- task: Npm@1
  displayName: 'NPM build assets'
  inputs:
    command: 'custom'
    customCommand: 'run build'
    workingDir: '$(frontend)'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(frontend)/dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop_reason-digital-news-vue-app'
    publishLocation: 'Container'